version: '3.8'
services:
    teco:
        build: .
        restart: unless-stopped
        working_dir: /usr/src/app/
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            .env
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
